<?xml version="1.0"?>
<package format="2">
    <name>triton_classifier</name>
    <version>1.0.0</version>
    <description>Triton Inference Client for Image Classification</description>
    <license>MIT</license>

    <url type="repository">https://github.com/whoigit/ros-triton-image-classifier</url>

    <maintainer email="rgovostes@whoi.edu">Ryan Govostes</maintainer>

    <author email="rgovostes@whoi.edu">Ryan Govostes</author>

    <buildtool_depend>catkin</buildtool_depend>

    <depend>rospy</depend>
    <depend>sensor_msgs</depend>
    <depend>vision_msgs</depend>

    <exec_depend>cv_bridge</exec_depend>

    <test_depend>python3-pytest</test_depend>
    <test_depend>python3-numpy</test_depend>
    <test_depend>python3-pil</test_depend>
</package>
